use QLBONgda
GO
/*vCAU1*/
CREATE VIEW vCau1 AS 
SELECT MACT, HOTEN,  NGAYSINH, DIACHI, VITRI
	FROM CAUTHU ct, CAULACBO clb, QUOCGIA qg
	WHERE clb.MACLB=ct.MACLB AND clb.TENCLB=N'SHB Đà Nẵng' and qg.MAQG=ct.MAQG AND qg.TENQG=N'Brazil'

/*vCAU2*/
CREATE VIEW vCau2 AS
SELECT MATRAN, NGAYTD, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TENSAN, KETQUA
	FROM TRANDAU td join SANVD san ON td.MASAN=san.MASAN
		JOIN CAULACBO CLB1 ON td.MACLB1 = CLB1.MACLB
		JOIN CAULACBO CLB2 ON td.MACLB2 = CLB2.MACLB
	WHERE VONG=3 AND NAM=2009

/*vCAU3*/
CREATE VIEW vCau3 AS 
SELECT hlv.MAHLV, TENHLV, NGAYSINH, DIACHI, VAITRO, TENCLB
	FROM HUANLUYENVIEN hlv, CAULACBO clb, HLV_CLB hlvclb
	WHERE hlvclb.MAHLV=hlv.MAHLV AND hlvclb.MACLB=clb.MACLB AND MAQG='VN'

/*vCAU4*/
CREATE VIEW vCau4 AS 
SELECT clb.MACLB, clb.TENCLB , svd.TENSAN , svd.DIACHI , COUNT(ct.MAQG) AS SOLUONG
	FROM CAULACBO clb, SANVD svd , CAUTHU ct, QUOCGIA q
	WHERE clb.MACLB = ct.MACLB and clb.MASAN = svd.MASAN and ct.MAQG = q.MAQG and q.MAQG <> 'VN' 
		GROUP BY clb.MACLB, clb.TENCLB, svd.TENSAN , svd.DIACHI
		HAVING  COUNT(ct.MAQG) > 1

/*vCAU5*/
CREATE VIEW vCau5 AS
SELECT TENTINH, COUNT(ct.VITRI) AS SOLUONG
	FROM TINH tinh, CAUTHU ct, CAULACBO clb
	WHERE VITRI=N'Tiền đạo' and tinh.MATINH=clb.MATINH and clb.MACLB=ct.MACLB
		GROUP BY TENTINH

/*vCAU6*/
CREATE VIEW vCau6 AS
SELECT  TENCLB, TENTINH
	FROM BANGXH xh, CAULACBO clb, tinh t
	WHERE VONG=3 AND xh.MACLB=clb.MACLB and t.MATINH=clb.MATINH and NAM=2009 and HANG=1

/*vCAU7*/
CREATE VIEW vCau7 AS
SELECT TENHLV
	FROM HUANLUYENVIEN
	WHERE DIENTHOAI IS NULL

/*vCAU8*/
CREATE VIEW vCau8 AS
SELECT TENHLV
	FROM  HUANLUYENVIEN hlv, HLV_CLB clbhlv
	WHERE MAQG='VN' AND clbhlv.MACLB IS NULL

/*vCAU9*/
CREATE VIEW vCau9 AS
SELECT CONVERT(date,NGAYTD,103) AS NGAYTD , CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TENSAN, KETQUA
	FROM TRANDAU td join SANVD san ON td.MASAN=san.MASAN
		JOIN CAULACBO CLB1 ON td.MACLB1 = CLB1.MACLB
		JOIN CAULACBO CLB2 ON td.MACLB2 = CLB2.MACLB
	WHERE VONG= 3 AND NAM=2009 AND MACLB1 IN(
		SELECT MACLB 
		FROM BANGXH
		WHERE VONG=3 AND NAM=2009 AND HANG=1

		)
	OR MACLB2 IN (
		SELECT MACLB
		FROM BANGXH
		WHERE VONG =3 AND NAM=2009 AND HANG=1
		)

 /*vCau10*/
 CREATE VIEW vCau10 AS
 SELECT CONVERT(date,NGAYTD,103) AS NGAYTD , CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TENSAN, KETQUA
	FROM TRANDAU td join SANVD san ON td.MASAN=san.MASAN
		JOIN CAULACBO CLB1 ON td.MACLB1 = CLB1.MACLB
		JOIN CAULACBO CLB2 ON td.MACLB2 = CLB2.MACLB
	WHERE VONG=3 AND NAM=2009 AND MACLB1 IN(
		SELECT TOP 1 MACLB
		FROM BANGXH
		WHERE VONG=3 AND NAM=2009
		ORDER BY HANG ASC
		)
	OR MACLB2 IN (
		SELECT TOP 1 MACLB
		FROM BANGXH
		WHERE VONG =3 AND NAM=2009
		ORDER BY HANG ASC
		)
